;METADATA=(Diff=true, UseCommands=true)
[/Script/TheIsle.TIGameSession]
ServerName=Primal Survival / 5x Growth / High AI / No Rules
bServerPassword=false
ServerPassword=
bServerDynamicWeather=true
ServerDayLengthMinutes=45
ServerNightLengthMinutes=20
MinWeatherVariationInterval=600
MaxWeatherVariationInterval=900
bServerWhitelist=false
bEnableGlobalChat=true
MapName=Gateway
MaxPlayerCount=250
bEnableHumans=true
bQueueEnabled=true
QueuePort=16008
QueryPort=16006
bRconEnabled=true
RconPassword=fef1272es1f
RconPort=16007
bSpawnPlants=true
bSpawnAI=true
AISpawnInterval=25
AISpawnMultiplier=8
bEnableMigration=true
MaxMigrationTime=5400
GrowthMultiplier=5
bEnableMutations=true
AIDensity=45
ServerAIMax=300
SpeciesMigrationTime=10800
bEnableMassMigration=true
MassMigrationTime=43200
MassMigrationDisableTime=7200
bEnablePatrolZones=true
bEnableDiets=true
bServerFallDamage=true
bAllowRecordingReplay=true
PlantSpawnMultiplier=15
bUseRegionSpawning=false
bUseRegionSpawnCooldown=true
RegionSpawnCooldownTimeSeconds=30
CorpseDecayMultiplier=10
Discord="https://discord.gg/JVMqmxzG5X"

[/script/theisle.tigamestatebase]
AdminsSteamIDs=76561198950212923
AdminsSteamIDs=76561199074797441
AdminsSteamIDs=76561199022940350
WhitelistIDs=76561198950212923
WhitelistIDs=76561199074797441
WhitelistIDs=76561199022940350
VIPs=76561198950212923
VIPs=76561199074797441
VIPs=76561199022940350
AllowedClasses=Dryosaurus
AllowedClasses=Hypsilophodon
AllowedClasses=Pachycephalosaurus
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Diabloceratops
AllowedClasses=Omniraptor
AllowedClasses=Pteranodon
AllowedClasses=Troodon
AllowedClasses=Beipiaosaurus
AllowedClasses=Gallimimus
AllowedClasses=Dilophosaurus
AllowedClasses=Herrerasaurus
AllowedClasses=Maiasaura
AllowedClasses=Triceratops
AllowedClasses=Allosaurus
AllowedClasses=Tyrannosaurus
